# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Teaching Exergy using TESPy
author: Francesco Witte, Malte Fritz, Jonas Freißmann, Mathias Hofmann, Ilja Tuschy, George Tsatsaronis
copyright: "2023"
logo: figures/logo_tespy_mid.svg
email: info@witte.sh

exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", LICENSE.md]

description: >- # this means to ignore newlines until "baseurl:"
  These are open educational resources on exergy and exergy analysis in thermodynamic processes.

execute_notebooks: auto

# LaTeX settings
bibtex_bibfiles:
   - references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/fwitte/TESPy_teaching_exergy  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "logo_tespy_small.svg"
  home_page_in_navbar: false

# Display plotly figures in book
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
